### ISSUE TITLE
Grabbing linux-docker which is too new for configuration file. 

### ISSUE THREAD

**Issue by psgivens** [Securing-DevOps/invoicer-chapter2#19]
AWS has evolved. This grep will now the pull the latest version of the docker linux. This is incompatible with the app-version.json file supplied because it complains that this value needs to be 2
[ "AWSEBDockerrunVersion": "1",](https://github.com/Securing-DevOps/invoicer-chapter2/blob/master/app-version.json#L2)

I suggest changing [this code](
https://github.com/Securing-DevOps/invoicer-chapter2/blob/310bf66cf4fdf418229547d2bd751e856db4912f/create_ebs_env.sh#L80):

    jq -r '.SolutionStacks[]' | grep -P '.+Amazon Linux.+Docker.+' | head -1)"

to this:

    jq -r '.SolutionStacks[]' | grep -P '.+Amazon Linux.+Docker.+v2\.7.+' | head -1)"

**Comment by jvehent** [comment]
Or maybe we could keep the grep as it is, and bump `app-version.json` to version 2?

**Comment by psgivens** [comment]
That would be recommended if you want to continue to maintain this repo. i.e. if it were a real project. 

The grep update relieves you of the obligation to watch for changes in AWS, while providing a repo that your readers can use without breaking. i.e. Are you going to notice, and update, this repo when a new version of docker requires a new version of the app-version?

**Comment by jvehent** [comment]
fixed in https://github.com/Securing-DevOps/invoicer-chapter2/commit/f2678d0cfa29fe393404b3baaf371b8fff446f7a
